# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod "JLStickerTextView", :git => "https://github.com/luiyezheng/JLStickerTextView.git"  

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
